"""
1. SELECT * FROM DARBUOTOJAI
2. SELECT GIMIMO_DATA FROM DARBUOTOJAI
3. SELECT VARDAS, PAVARDĖ, GIMIMO_DATA FROM DARBUOTOJAI
4. SELECT DISTINCT SKYRIUS_PAVADINIMAS FROM DARBUOTOJAI
5. SELECT * FROM DARBUOTOJAI WHERE SKYRIUS_PAVADINIMAS = "Gamybos"
6. SELECT * FROM DARBUOTOJAI WHERE VARDAS = "Giedrius"
7. SELECT * FROM DARBUOTOJAI WHERE GIMIMO_DATA = "1986-09-19"
8. SELECT * FROM DARBUOTOJAI WHERE PAVARDĖ = "Sabutis"
9. SELECT VARDAS, PAVARDĖ FROM DARBUOTOJAI WHERE SKYRIUS_PAVADINIMAS = "Gamybos"
10. INSERT INTO DARBUOTOJAI(VARDAS, PAVARDĖ, GIMIMO_DATA, PAREIGOS, SKYRIUS_PAVADINIMAS) VALUES ("Robert", "Mlynovskij","1997-12-16","Programuotojas", "Gamybos")
11. INSERT INTO DARBUOTOJAI(VARDAS, PAVARDĖ, GIMIMO_DATA) VALUES ("Tomas", "Destytojas","1996-11-16")
12. UPDATE DARBUOTOJAI SET PAREIGOS = "Lecturer", SKYRIUS_PAVADINIMAS = "Python" WHERE VARDAS = "Tomas" AND PAVARDĖ = "Destytojas";
13. DELETE FROM DARBUOTOJAI WHERE VARDAS = "Tomas" AND PAVARDĖ = "Destytojas"
14.INSERT INTO DARBUOTOJAI (VARDAS, PAVARDĖ, PAREIGOS)
    VALUES ("Jonas", "Antanaitis", "Programuotojas"),
            ("Petras", "Antanaitis", "Programuotojas")
15. UPDATE DARBUOTOJAI SET PAREIGOS = "Testuotojas" WHERE PAVARDĖ = "Antanaitis"
16. SELECT count(*) FROM DARBUOTOJAI WHERE PAREIGOS = "Testuotojas"





"""
